# Site settings
title: Arthur Pachachura - The Comp Life
email: pachachura.arthur@gmail.com
description: "Arthur Pachachura's Awesome Blog for AP Computer Science"
baseurl: ""
url: "http://arthurpachachura.com"
github_username:  smo-key

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
timezone: America/Chicago
lsi: true
